name: Update Releases, Build and push Image to Docker registry

on:
  push:
    tags:
      - 'v*'

jobs:

  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.22.4' ]

    steps:
      - name: Checkout code
        uses: actions/Checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
         go-version: ${{ matrix.go-version }}

      - name: Display Go version
        run:  go version

      - name: Install dependencies
        run:  go mod download

      - name: Build Binaries
        run:  make build-all

      - name: Create release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        with:
          body_path: CHANGELOG.md
          files: |
            dist/checkemailbot-linux-amd64.zip
            dist/checkemailbot-windows-amd64.zip
            dist/checkemailbot-darwin-amd64.zip
            dist/checkemailbot-darwin-arm64.zip

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64,darwin/amd64,darwin/arm64,linux/arm/v7
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/checkemailbot:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/checkemailbot:${{ github.ref_name }}




